### ISSUE TITLE
Link GLM to AED

### ISSUE THREAD

**Issue by jsta** [jsta/GLM_docker#1]
Possibly as easy as adding the following lines:

```
WORKDIR ../libaed2
RUN make
```

**Comment by robertladwig** [comment]
I tried your updated GLM container and although the building seemed to be successful, when I run it using a AED2 setup I still get this error:
       ----------------------------------------------------
       |  General Lake Model (GLM)   Version 3.0.0beta12  |
       ----------------------------------------------------
glm built using gcc version 7.4.0

Reading config from glm3.nml
nDays 1230 timestep 3600.000000
Maximum lake depth is 19.288000
Depth where flow will occur over the crest is 18.288000
VolAtCrest= 6287794.50694, and Max Lake Vol= 6631615.29144 (m3)
No snow and ice section, setting default parameters and assuming no snowfall
*starting sediment =    5.00000
*starting sediment =    0.10000
Sediment section present, simulating sediment heating
*sed_temp_mean =    4.50000
*sed_temp_mean =    5.00000
AED2 not supported in this build

**Comment by robertladwig** [comment]
I could run AED2 by changing some parts of your container, see https://github.com/robertladwig/GLM_docker/blob/master/Dockerfile 

```
WORKDIR libutil

RUN F90=gfortran-8 make

WORKDIR ../libplot

RUN make

WORKDIR ../libaed2

RUN F90=gfortran-8 make

WORKDIR ../GLM

RUN FC=gfortran-8 ./build_glm.sh
```

**Comment by jsta** [comment]
Thanks!
